force-app/main/default/objects/Pagamento__c/Pagamento__c.object-meta.xml
<CustomObject>
    <label>Pagamento</label>
    <nameField>
        <displayFormat>PG-{000000000}</displayFormat>
        <label>Número do Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>V-{000000000}</displayFormat>
        <label>Número da Viagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/fields/Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Companhia__c.field-meta.xml
<CustomField>
    <fullName>Companhia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Companhia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Companhia</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Custo__c.field-meta.xml
<CustomField>
    <fullName>Custo__c</fullName>
    <inlineHelpText>Custo em reais da viagem da ida/volta.</inlineHelpText>
    <label>Custo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Ida__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Ida__c</fullName>
    <label>Data/Hora da Ida</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Volta__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Volta__c</fullName>
    <label>Data/Hora da Volta</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Estado_de_Destino__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Destino__c</fullName>
    <label>Estado de Destino</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Pago_pela_empresa__c.field-meta.xml
<CustomField>
    <fullName>Pago_pela_empresa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pago pela empresa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GestaoDeViagensCTRL.cls
public class GestaoDeViagensCTRL {

    @AuraEnabled
    public static List<Viagem__c> exibirViagensRealizadas(String ano, String mes, String estado){
        
        Map<String, Integer> mapMesString = new Map<String, Integer>();
        
        mapMesString.put('Janeiro', 1);
        mapMesString.put('Fevereiro', 2);
        mapMesString.put('Março', 3);
        mapMesString.put('Abril', 4);
        mapMesString.put('Maio', 5);
        mapMesString.put('Junho', 6);
        mapMesString.put('Julho', 7);
        mapMesString.put('Agosto', 8);
        mapMesString.put('Setembro', 9);
        mapMesString.put('Outubro', 10);
        mapMesString.put('Novembro', 11);
        mapMesString.put('Dezembro', 12);
        
        List<Viagem__c> viagens = new List<Viagem__c>();

        List<Viagem__c> viagensRealizadasMensal = [SELECT Id, Name, Data_Hora_da_Ida__c, Data_Hora_da_Volta__c, Custo__c, Estado_de_Destino__c, Pago_pela_empresa__c, Companhia__c, Companhia__r.Name, Pagamento__c, Colaborador__r.FirstName
                                                  FROM Viagem__c 
                                                  WHERE Pago_pela_empresa__c = true
                                                  AND Pagamento__c != null
                                                  AND Estado_de_Destino__c = :estado
                                                 ];

        for(Viagem__c viagem : viagensRealizadasMensal){
            Datetime dataViagem = Datetime.newInstance(Integer.valueOf(ano), mapMesString.get(mes), viagem.Data_Hora_da_Ida__c.day());
            String dateStr = dataViagem.format('yyyy-MM-dd hh:ss');
            System.debug('Data viagem 1 ' + dataViagem);

            String dataIda = viagem.Data_Hora_da_Ida__c.format('yyyy-MM-dd hh:ss');
            System.debug('data ida formatada:'+dataIda);
            System.debug('Comparação das datas:'+dateStr);
            if(dataIda == dateStr){
                viagem.Data_Hora_da_Ida__c = dataViagem;
                viagens.add(viagem);
            }

            System.debug('Data viagem ' + dataViagem);
        }

        System.debug('Estado ' + estado);
        System.debug('Viagens realizadas ' + viagensRealizadasMensal);

        if(viagens.isEmpty()){
            throw new AuraHandledException('Você não possui viagens nesse período.');
        }       
        
        return viagens;
    }
}