force-app/main/default/objects/Account/recordTypes/Cliente.recordType-meta.xml
<RecordType>
    <fullName>Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Versões do conteúdo</relationshipLabel>
    <relationshipName>Versoes_do_conteudo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Despesa__c/Despesa__c.object-meta.xml
<CustomObject>
    <label>Despesa</label>
    <nameField>
        <label>Nome da despesa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Despesa__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Viagem__c.field-meta.xml
<CustomField>
    <fullName>Viagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Viagem</label>
    <referenceTo>Viagem__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/Pagamento__c.object-meta.xml
<CustomObject>
    <label>Pagamento</label>
    <nameField>
        <displayFormat>PG-{000000000}</displayFormat>
        <label>Número do Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pagamento__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pagamentos</relationshipLabel>
    <relationshipName>Pagamentos1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>V-{000000000}</displayFormat>
        <label>Número da Viagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Viagens (Cliente)</relationshipLabel>
    <relationshipName>Viagens1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Custo__c.field-meta.xml
<CustomField>
    <fullName>Custo__c</fullName>
    <inlineHelpText>Custo em reais da viagem da ida/volta.</inlineHelpText>
    <label>Custo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PDFPagamentoExtension.cls
public class PDFPagamentoExtension { //criar classe de teste
    
    private Pagamento__c pagamento;
    public List<Attachment> existingAttLst { get; set; }
    public List<ContentVersion> existingContentLst { get; set; }
    public Blob pdfBlob;
	
    public PDFPagamentoExtension(ApexPages.StandardController stdController) {
        this.pagamento = (Pagamento__c) stdController.getRecord();
    }
    
    
    public Decimal getValorBoleto() {
        Id pagamentoId = this.pagamento.Id;
        
        AggregateResult[] agrupamentoViagem = [SELECT SUM(Custo__c) custo
                                         FROM Viagem__c
                                         WHERE Pagamento__c = :pagamentoId];
        
        Decimal totalCustoViagem = (Decimal) agrupamentoViagem[0].get('custo');
        
        AggregateResult[] agrupamentoDespesa = [SELECT SUM(Custo__c) custo
                                         FROM Despesa__c
                                         WHERE Pagamento__c = :pagamentoId];
        
        Decimal totalCustoDespesa = (Decimal) agrupamentoDespesa[0].get('custo');
        
        if(totalCustoDespesa == null) {
            totalCustoDespesa = 0;
        }
        
        if (totalCustoViagem == null) {
            totalCustoViagem = 0;
        }
        
        return totalCustoViagem + totalCustoDespesa;

    }
    
    	public PageReference attachPDF() {
		
		PageReference pdfPage = Page.PDFPagamento;
        pdfPage.getParameters().put('id', this.pagamento.Id);
            
            
		if (!Test.isRunningTest()) {            
                
            try {
				this.pdfBlob = pdfPage.getContent(); 
            }
            catch (Exception e) {
                this.pdfBlob = Blob.valueOf(e.getMessage());
            }
            
                
            /*List<ContentVersion> lstCV = [SELECT Id, ContentDocumentId, Title, VersionData FROM ContentVersion WHERE Pagamento__c = :this.pagamento.Id];
                
                if(lstCV.size() == 0) {
                    List<ContentDocumentLink> cdls = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :this.pagamento.Id];
                    Set<Id> cdIds = new Set<Id>();
                    for(ContentDocumentLink cdl : cdls) {
                        cdIds.add(cdl.ContentDocumentId);
                    }
                    lstCV = [SELECT Id, ContentDocumentId, Title, VersionData FROM ContentVersion WHERE ContentDocumentId IN :cdIds];
                    
                      for(ContentVersion cVersion : lstCV) {
                         cVersion.ContentLocation = 'S';
                         cVersion.Title = 'Boleto - ' + this.pagamento.Cliente__r.Name;
                         cVersion.PathOnClient = cVersion.Title + '.pdf';
                         cVersion.VersionData = this.pdfBlob; //converte o arquivo de string para pdf
                         insert cVersion;
                    }
                            
                }  */                      
                            
            ContentVersion cVersion = new ContentVersion();
            cVersion.ContentLocation = 'S';
            cVersion.Title = 'Boleto - ' + this.pagamento.Cliente__r.Name;
            cVersion.PathOnClient = cVersion.Title + '.pdf';
            cVersion.VersionData = this.pdfBlob; //converte o arquivo de string para pdf
            insert cVersion;
            
            Id conDocument = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cVersion.Id].contentDocumentId;
            ContentDocumentLink cDocLink = new ContentDocumentLink();
            cDocLink.ContentDocumentId = conDocument;
            cDocLink.LinkedEntityId = this.pagamento.Id; //Id do objeto
            cDocLink.Visibility = 'AllUsers'; // visibilidade para todos os usuários
            cDocLink.ShareType = 'V'; //permissão de apenas visualizar "V"
            insert cDocLink;                
           
            //System.debug('Documento já anexado.');
            //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Documento já anexado.'));
    


            
		} else {
			this.pdfBlob = Blob.valueOf('Texto de teste para arquivo PDF...');
		}
                       
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'PDF gerado e anexado com sucesso.'));
		
		//redirect the user
		//PageReference pageWhereWeWantToGo = new ApexPages.StandardController(this.pagamento).view(); //we want to redirect the User back to the Account detail page
		//pageWhereWeWantToGo.setRedirect(true); //indicate that the redirect should be performed on the client side
		//return pageWhereWeWantToGo; //send the User on their way
		return pdfPage;
	}
    
    public PageReference sendEmail(){
        
        Pagamento__c pagamentoWithClientEmail = [SELECT Id, Cliente__r.Email__c FROM Pagamento__c WHERE Id = :this.pagamento.Id LIMIT 1];
        
        if (pagamentoWithClientEmail != null && pagamentoWithClientEmail.Cliente__r.Email__c != null) {
        String email = pagamentoWithClientEmail.Cliente__r.Email__c;
        List<String> emails = new List<String>();
        emails.add(email);
        
        PageReference pdfPage = Page.PDFPagamento;
        pdfPage.getParameters().put('id', this.pagamento.Id);
        this.pdfBlob = pdfPage.getContentAsPDF(); 
               
        // Create email
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setToAddresses(emails);
        message.setSubject('Resumo de pagamento para ' + this.pagamento.Cliente__r.Name);
        message.setHtmlBody('Segue o resumo de pagamento e o boleto para ' + this.pagamento.Cliente__r.Name + '. Dúvidas, retornar este email.');
        
        // Attach PDF to email and send
        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        attachment.setContentType('application/pdf');
        attachment.setFileName('Resumo do pagamento -' + this.pagamento.Cliente__r.Name + '.pdf');
        attachment.setInline(false);
        attachment.setBody(this.pdfBlob);
        message.setFileAttachments(new Messaging.EmailFileAttachment[]{ attachment });
        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{ message });
        
        ApexPages.addMessage(new 
            ApexPages.Message(ApexPages.Severity.INFO,
           'Email enviado com anexo em PDF para ' + email)); 
                        
        } else {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Email do cliente não encontrado.'
            ));
        }                

		PageReference pageWhereWeWantToGo = new ApexPages.StandardController(this.pagamento).view(); 
		pageWhereWeWantToGo.setRedirect(true);
		return pageWhereWeWantToGo;    	
    
    }    
	
    /*public void savePdf() {
        
        // Recuperar o conteúdo do PDF da variável view state
        String pdfContent = EncodingUtil.base64Encode(this.pdfContent);
        
        // Converte o conteúdo base64 de volta para Blob
        Blob pdfBlob = EncodingUtil.base64Decode(pdfContent);
        
        //String testData = 'this will be stored in pdf'; //deve conter o arquivo do boleto
        ContentVersion cVersion = new ContentVersion();
        cVersion.ContentLocation = 'S';
        cVersion.Title = 'PDFPagamento';
        cVersion.PathOnClient = cVersion.Title + '.pdf';
        cVersion.VersionData = pdfBlob; //converte o arquivo de string para pdf
        insert cVersion;
        
        Id conDocument = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cVersion.Id].contentDocumentId;
        ContentDocumentLink cDocLink = new ContentDocumentLink();
        cDocLink.ContentDocumentId = conDocument;
        cDocLink.LinkedEntityId = this.pagamento.Id; //Id do objeto
        cDocLink.Visibility = 'AllUsers'; // visibilidade para todos os usuários
        cDocLink.ShareType = 'V'; //permissão de apenas visualizar "V"
        insert cDocLink;
    }*/
    
    /*public PageReference gerarPDF() {
        // Recuperar o conteúdo do PDF da variável view state
        String pdfContent = EncodingUtil.base64Encode(this.pdfContent);
        
        // Converte o conteúdo base64 de volta para Blob
        Blob pdfBlob = EncodingUtil.base64Decode(pdfContent);
        
    // Lógica para gerar o PDF
    //String pdfContent = 'Conteúdo do PDF gerado'; // Substitua pelo conteúdo real do PDF
    //pdfContent = EncodingUtil.base64Encode(Blob.valueOf(pdfContent)); // Converter para base64
    this.pdfContent = pdfBlob;
        
    savePdf();
    return null;
}*/
    
    
    
}