force-app/main/default/objects/Despesa__c/Despesa__c.object-meta.xml
<CustomObject>
    <label>Despesa</label>
    <nameField>
        <label>Nome da despesa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Despesa__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Pago__c.field-meta.xml
<CustomField>
    <fullName>Pago__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indica quando a despesa for paga pela empresa.</inlineHelpText>
    <label>Pago</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Pago pelo colaborador</fullName>
            </value>
            <value>
                <fullName>Pago_pela_empresa</fullName>
                <label>Pago pela empresa</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Viagem__c.field-meta.xml
<CustomField>
    <fullName>Viagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Viagem</label>
    <referenceTo>Viagem__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/Pagamento__c.object-meta.xml
<CustomObject>
    <label>Pagamento</label>
    <nameField>
        <displayFormat>PG-{000000000}</displayFormat>
        <label>Número do Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pagamento__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando Pagamento</fullName>
                <default>true</default>
                <label>Aguardando Pagamento</label>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>V-{000000000}</displayFormat>
        <label>Número da Viagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Pago_pela_empresa__c.field-meta.xml
<CustomField>
    <fullName>Pago_pela_empresa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pago pela empresa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PagamentoTriggerAlteraPagamento.cls
public class PagamentoTriggerAlteraPagamento {
	private List<Pagamento__c> newListPagamento;
    private Map<Id, Pagamento__c> oldMapPagamento;
    private Map<Id, Pagamento__c> filteredMapPagamento = new Map<Id, Pagamento__c>();
    private Boolean hasRecords;
    
    public PagamentoTriggerAlteraPagamento(List<Pagamento__c> newListPagamento, Map<Id, Pagamento__c> oldMapPagamento) {
        this.newListPagamento = newListPagamento;
        this.oldMapPagamento = oldMapPagamento;
        filter();
        this.hasRecords = (filteredMapPagamento.isEmpty()) ? false : true;
    }
    
    private void filter() {
        
        for(Pagamento__c pagamento : newListPagamento) {
            String valorAntigoPagamentoPago = oldMapPagamento.get(pagamento.Id).Status__c;
            
            if(pagamento.Status__c == 'Pago' && pagamento.Status__c != valorAntigoPagamentoPago) {
				filteredMapPagamento.put(pagamento.Id, pagamento);
            }
          }                
        }    
    
    
    public void run() {
        if(hasRecords) {            
            List<Viagem__c> viagemFiltrada = [SELECT Id FROM Viagem__c WHERE Pagamento__c IN :filteredMapPagamento.keySet()];
            List<Despesa__c> despesaFiltrada = [SELECT Id FROM Despesa__c WHERE Pagamento__c IN :filteredMapPagamento.keySet()];
            
            if(!viagemFiltrada.isEmpty()) {
                
            for(Viagem__c viagem : viagemFiltrada) {
                viagem.Pago_pela_empresa__c = true;
            	update viagemFiltrada;
            	}     
            }

            if(!despesaFiltrada.isEmpty()) {
                
            for(Despesa__c despesa : despesaFiltrada) {
               despesa.Pago__c = true;
               despesa.Status__c = 'Pago_pela_empresa';
               update despesaFiltrada;
           		 }           
            }
            
        }
    }
  
}