force-app/main/default/objects/Despesa__c/Despesa__c.object-meta.xml
<CustomObject>
    <label>Despesa</label>
    <nameField>
        <label>Nome da despesa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Despesa__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Pago pelo colaborador</fullName>
            </value>
            <value>
                <fullName>Pago_pela_empresa</fullName>
                <label>Pago pela empresa</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Viagem__c.field-meta.xml
<CustomField>
    <fullName>Viagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Viagem</label>
    <referenceTo>Viagem__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/Pagamento__c.object-meta.xml
<CustomObject>
    <label>Pagamento</label>
    <nameField>
        <displayFormat>PG-{000000000}</displayFormat>
        <label>Número do Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pagamento__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando Pagamento</fullName>
                <default>true</default>
                <label>Aguardando Pagamento</label>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pagamento__c/fields/Valor_Total_Despesas__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total_Despesas__c</fullName>
    <label>Valor Total Despesas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/fields/Valor_Total_Viagens__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total_Viagens__c</fullName>
    <label>Valor Total Viagens</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>V-{000000000}</displayFormat>
        <label>Número da Viagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/fields/Custo__c.field-meta.xml
<CustomField>
    <fullName>Custo__c</fullName>
    <inlineHelpText>Custo em reais da viagem da ida/volta.</inlineHelpText>
    <label>Custo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PagamentoTriggerAdicionaCusto.cls
public class PagamentoTriggerAdicionaCusto {
    
    private List<Pagamento__c> newListPagamento;
    private Map<Id, Pagamento__c> oldMapPagamento;
    private Map<Id, Decimal> mapViagemCusto = new Map<Id, Decimal>();
    private Map<Id, Decimal> mapDespesaCusto = new Map<Id, Decimal>();
    private List<Pagamento__c> pagamentosToUpdate = new List<Pagamento__c>();
	
    public PagamentoTriggerAdicionaCusto(List<Pagamento__c> newListPagamento, Map<Id, Pagamento__c> oldMapPagamento) {
       this.newListPagamento = newListPagamento;
       this.oldMapPagamento = oldMapPagamento;
       filter();
    }
    
    private void filter() {
        
        for(Pagamento__c pagamento : newListPagamento){
            //String valorAntigoPagamentoPago = oldMapPagamento.get(pagamento.Id).Status__c != null ? oldMapPagamento.get(pagamento.Id).Status__c : 'Aguardando Pagamento'; 
            
            if(pagamento.Status__c == 'Pago' /*&& pagamento.Status__c != valorAntigoPagamentoPago*/) {

                for (AggregateResult result : [SELECT Pagamento__c, SUM(Custo__c) FROM Viagem__c WHERE Pagamento__c = :pagamento.Id GROUP BY Pagamento__c]) {
                    this.mapViagemCusto.put((Id) result.get('Pagamento__c'), (Decimal) result.get('expr0'));
                }

                for (AggregateResult result : [SELECT Pagamento__c, SUM(Custo__c) FROM Despesa__c WHERE Pagamento__c = :pagamento.Id GROUP BY Pagamento__c]) {
                    this.mapDespesaCusto.put((Id) result.get('Pagamento__c'), (Decimal) result.get('expr0'));
                }
                
                this.pagamentosToUpdate.add(pagamento);
            }
        }
        
    }
    
    public void run() {

        for (Pagamento__c pagamento : pagamentosToUpdate) {
        	Decimal valorTotalCustoViagem = mapViagemCusto.get(pagamento.Id) != null ? mapViagemCusto.get(pagamento.Id) : 0;
            System.debug('Valor Viagem' + valorTotalCustoViagem);
			Decimal valorTotalCustoDespesa = mapDespesaCusto.get(pagamento.Id) != null ? mapDespesaCusto.get(pagamento.Id) : 0;
            
            pagamento.Valor_Total_Viagens__c = valorTotalCustoViagem;
            pagamento.Valor_Total_Despesas__c = valorTotalCustoDespesa;
            
            update pagamento;
        }
        
     //update pagamentosToUpdate;
                       
    }   
}