force-app/main/default/objects/Account/fields/Limite_de_Credito__c.field-meta.xml
<CustomField>
    <fullName>Limite_de_Credito__c</fullName>
    <label>Limite de Crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Data_Limite_de_Envio__c.field-meta.xml
<CustomField>
    <fullName>Data_Limite_de_Envio__c</fullName>
    <label>Data Limite de Envio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Limite_de_Credito__c.field-meta.xml
<CustomField>
    <fullName>Limite_de_Credito__c</fullName>
    <formula>Account.Limite_de_Credito__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Limite de Crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BatchEnviarNotifDataLimiteEnvioTest.cls
@isTest
public class BatchEnviarNotifDataLimiteEnvioTest {
	@TestSetup
    static void makeData() {
        Account conta = new Account();
        conta.Name = 'Rachel Lizandra';
        conta.Limite_de_Credito__c = 10000;
        conta.Status__c = 'Ativo';
        insert conta;
        
        Opportunity opp = new Opportunity();
        opp.AccountId = conta.Id;
        opp.Name = 'Teste enviar notificação';
        opp.StageName = 'Prospecting';
        opp.Data_Limite_de_Envio__c = System.now().addMinutes(30);
        opp.CloseDate = System.Today().addDays(10);
        insert opp;
    }
    
    @isTest
    public static void batchEnviarNotificacaoDataEnvioLimite() {
        
        Test.startTest();
        BatchEnviarNotificacaoDataLimiteEnvio batchJob = new BatchEnviarNotificacaoDataLimiteEnvio();
        //System.scheduleBatch(batchJob, 'BatchEnviarNotificacaoDataLimiteEnvio' + Datetime.now(), 30, 200);
        Database.executeBatch(batchJob);
        Test.stopTest();
        
        List<AsyncApexJob> aJList = [SELECT ApexClassId, Id, Status FROM AsyncApexJob WHERE ApexClassId IN (SELECT Id FROM ApexClass WHERE Name = 'BatchEnviarNotificacaoDataLimiteEnvio')];
        if (!aJList.isEmpty()) {
            System.assertEquals('Completed', aJList[0].Status);
        }
    }
}