force-app/main/default/objects/Account/fields/Limite_de_Credito__c.field-meta.xml
<CustomField>
    <fullName>Limite_de_Credito__c</fullName>
    <label>Limite de Crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Porte_da_empresa__c.field-meta.xml
<CustomField>
    <fullName>Porte_da_empresa__c</fullName>
    <inlineHelpText>Pequeno (até 50 funcionários)
Médio (50 – 200 funcionários)
Grande (&gt; 200 funcionários)</inlineHelpText>
    <label>Porte da empresa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pequeno</fullName>
            </value>
            <value>
                <fullName>Médio</fullName>
            </value>
            <value>
                <fullName>Grande</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_Companhia__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Companhia__c</fullName>
    <label>Tipo de Companhia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aérea</fullName>
            </value>
            <value>
                <fullName>Rodoviária</fullName>
            </value>
            <value>
                <fullName>Aplicativo de transporte</fullName>
            </value>
            <value>
                <fullName>Ferroviário</fullName>
            </value>
            <value>
                <fullName>Pluvial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Despesa__c/Despesa__c.object-meta.xml
<CustomObject>
    <label>Despesa</label>
    <nameField>
        <label>Nome da despesa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Despesa__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Data_da_Despesa__c.field-meta.xml
<CustomField>
    <fullName>Data_da_Despesa__c</fullName>
    <label>Data da Despesa</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Pago__c.field-meta.xml
<CustomField>
    <fullName>Pago__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indica quando a despesa for paga pela empresa.</inlineHelpText>
    <label>Pago</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Pago pelo colaborador</fullName>
            </value>
            <value>
                <fullName>Pago_pela_empresa</fullName>
                <label>Pago pela empresa</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Viagem__c.field-meta.xml
<CustomField>
    <fullName>Viagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Viagem</label>
    <referenceTo>Viagem__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/Pagamento__c.object-meta.xml
<CustomObject>
    <label>Pagamento</label>
    <nameField>
        <displayFormat>PG-{000000000}</displayFormat>
        <label>Número do Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pagamento__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pagamentos</relationshipLabel>
    <relationshipName>Pagamentos1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando Pagamento</fullName>
                <default>true</default>
                <label>Aguardando Pagamento</label>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>V-{000000000}</displayFormat>
        <label>Número da Viagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Viagens (Cliente)</relationshipLabel>
    <relationshipName>Viagens1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Companhia__c.field-meta.xml
<CustomField>
    <fullName>Companhia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Companhia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Companhia</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Custo__c.field-meta.xml
<CustomField>
    <fullName>Custo__c</fullName>
    <inlineHelpText>Custo em reais da viagem da ida/volta.</inlineHelpText>
    <label>Custo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Ida__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Ida__c</fullName>
    <label>Data/Hora da Ida</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Volta__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Volta__c</fullName>
    <label>Data/Hora da Volta</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <label>Cidade de Destino</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <label>Cidade de Origem</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Pago_pela_empresa__c.field-meta.xml
<CustomField>
    <fullName>Pago_pela_empresa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pago pela empresa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PagamentoTriggerAlteraPagamentoTest.cls
@isTest
public class PagamentoTriggerAlteraPagamentoTest {
	
    @TestSetup
    public static void setup() {
        
        Account contaCliente = new Account();
        contaCliente.RecordTypeId = '012Hs000000pezqIAA';
        contaCliente.Name = 'Rachel Lizandra';
        contaCliente.Status__c = 'Ativo';
        contaCliente.Porte_da_empresa__c = 'Pequeno';
        contaCliente.Limite_de_Credito__c = 4000.50;
        insert contaCliente;
        
        Account contaCompanhia = new Account();
        contaCompanhia.RecordTypeId = '012Hs000000pezvIAA';
        contaCompanhia.Name = 'GOL';
        contaCompanhia.Tipo_de_Companhia__c = 'Aérea';
        insert contaCompanhia;
        
        Contact contato = new Contact();
        contato.LastName = 'Teste';
        contato.AccountId = contaCliente.Id;
        insert contato;
        
        Pagamento__c pagamento = new Pagamento__c();
        pagamento.Cliente__c = contaCliente.Id; 
        pagamento.Status__c = 'Aguardando Pagamento';
        insert pagamento;
        
        Viagem__c viagem = new Viagem__c();
        viagem.Cliente__c = contaCliente.Id;
        viagem.Colaborador__c = contato.Id;
        viagem.Companhia__c = contaCompanhia.Id;
        viagem.Custo__c = 100;
        viagem.Data_Hora_da_Ida__c = System.now().addDays(1);
        viagem.Data_Hora_da_Volta__c = viagem.Data_Hora_da_Ida__c.addDays(4);
		viagem.Origem__c = 'Origem Teste Pagamento';
        viagem.Destino__c = 'Destino Teste Pagamento';
        viagem.Pagamento__c = pagamento.Id;
        insert viagem;
        
        Despesa__c despesa = new Despesa__c();
        despesa.Name = 'Hotel California';
        despesa.Cliente__c = contaCliente.Id;
        despesa.Colaborador__c = contato.Id;
        despesa.Custo__c = 300;
        despesa.Viagem__c = viagem.Id;
        despesa.Status__c = 'Novo';
        despesa.Data_da_Despesa__c = System.today().addDays(2);
        despesa.Descricao__c = 'testando despesa';
        despesa.Pagamento__c = pagamento.Id;
        insert despesa;
        
    }
    
    @isTest
    public static void validarAlteracaoDePagamentoViagemEDespesaUpdate() {
        
        List<Viagem__c> viagensPagasAntesDeRealizarPagamento = [SELECT Id, Pago_pela_empresa__c FROM Viagem__c WHERE Pago_pela_empresa__c = true];
        List<Despesa__c> despesasPagasAntesDeRealizarPagamento = [SELECT Id, Pago__c FROM Despesa__c WHERE Pago__c = true];
        
        System.assertEquals(0, viagensPagasAntesDeRealizarPagamento.size(), 'Até o momento nenhuma viagem foi paga');
        System.assertEquals(0, despesasPagasAntesDeRealizarPagamento.size(), 'Até o momento nenhuma despesa foi paga');
        
        Pagamento__c pagamento = [SELECT Id, Status__c FROM Pagamento__c];
        
        pagamento.Status__c = 'Pago';
        update pagamento;
        
        List<Viagem__c> viagensPagasAposRealizarPagamento = [SELECT Id, Pago_pela_empresa__c FROM Viagem__c WHERE Pago_pela_empresa__c = true];
        List<Despesa__c> despesasPagasAposRealizarPagamento = [SELECT Id, Pago__c FROM Despesa__c WHERE Pago__c = true];
        
        System.assertEquals(1, viagensPagasAposRealizarPagamento.size(), 'Até o momento uma viagem foi paga');
        System.assertEquals(1, despesasPagasAposRealizarPagamento.size(), 'Até o momento uma despesa foi paga');
        
    }
}