force-app/main/default/objects/Account/fields/Limite_de_Credito__c.field-meta.xml
<CustomField>
    <fullName>Limite_de_Credito__c</fullName>
    <label>Limite de Crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>V-{000000000}</displayFormat>
        <label>Número da Viagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Viagens (Cliente)</relationshipLabel>
    <relationshipName>Viagens1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Custo__c.field-meta.xml
<CustomField>
    <fullName>Custo__c</fullName>
    <inlineHelpText>Custo em reais da viagem da ida/volta.</inlineHelpText>
    <label>Custo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Ida__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Ida__c</fullName>
    <label>Data/Hora da Ida</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Volta__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Volta__c</fullName>
    <label>Data/Hora da Volta</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <label>Cidade de Destino</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <label>Cidade de Origem</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ViagemTriggerValidaDataHoraTest.cls
@isTest
public class ViagemTriggerValidaDataHoraTest {
	//Objetos classes de teste
	//1 - Cobrir os cenários de negócios, ou seja, codificar um cenário similar ao real para validar o código criado
	//2 - Cobrir o código (cobrir as linhas de código) - Code coverage
	
    @TestSetup
    public static void setup() { //método que inicializa/prepara os registros que serão utilizados para cenário
		        
        //Conta, Contato da conta, Viagem
        Account conta = new Account();
        conta.Name = 'Thamires Tavares';
        conta.Limite_de_Credito__c = 10000;
        conta.Status__c = 'Ativo';
        insert conta;
        
        Contact contato = new Contact();
        contato.LastName = 'Teste';
        contato.AccountId = conta.Id;
        insert contato;
        
        Viagem__c viagem = new Viagem__c();
        viagem.Cliente__c = conta.Id;
        viagem.Colaborador__c = contato.Id;
        viagem.Custo__c = 100;
        viagem.Data_Hora_da_Ida__c = System.now().addDays(5);
        viagem.Data_Hora_da_Volta__c = viagem.Data_Hora_da_Ida__c.addDays(2);
		viagem.Origem__c = 'Origem Teste';
        viagem.Destino__c = 'Destino Teste';
        insert viagem;

    }
    
    @isTest
    public static void validarDataHoraInferiorDataIdaInsert() {
		Viagem__c viagem = [SELECT Data_Hora_da_Ida__c, Data_Hora_da_Volta__c FROM Viagem__c LIMIT 1];
        
        viagem.Data_Hora_da_Volta__c = viagem.Data_Hora_da_Ida__c.addDays(-3); //forçando o erro
        
        try {
            insert viagem;
        } catch(Exception e) {
            String error = e.getMessage();
            System.assert(error.contains('A data de volta não pode ser inferior a data de ida.'), 'Deve conter a mensagem "A data de volta não pode ser inferior a data de ida!"');
        }
    }
    
    @isTest
    public static void validarDataHoraInferiorDataIdaUpdate() {
        Viagem__c viagem = [SELECT Data_Hora_da_Ida__c, Data_Hora_da_Volta__c FROM Viagem__c LIMIT 1];
        
        viagem.Data_Hora_da_Volta__c = viagem.Data_Hora_da_Ida__c.addDays(-3); //forçando o erro
        
        try{
            update viagem;
        }catch(Exception e){
            String error = e.getMessage();
            System.assert(error.contains('A data de volta não pode ser inferior a data de ida.'), 'Deve conter a mensagem "A data de volta não pode ser inferior a data de ida!"');
        }
	}
}