force-app/main/default/objects/Account/fields/Porte_da_empresa__c.field-meta.xml
<CustomField>
    <fullName>Porte_da_empresa__c</fullName>
    <inlineHelpText>Pequeno (até 50 funcionários)
Médio (50 – 200 funcionários)
Grande (&gt; 200 funcionários)</inlineHelpText>
    <label>Porte da empresa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pequeno</fullName>
            </value>
            <value>
                <fullName>Médio</fullName>
            </value>
            <value>
                <fullName>Grande</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EstudosDML.cls
public class EstudosDML {
	// INSERT, UPDATE, DELETE
    public static Id createAccount(String name, String porteEmpresa, String status) {
        Account conta = new Account();
        conta.Name = name;
        conta.Porte_da_empresa__c = porteEmpresa;
        conta.Status__c = status;
        
        insert conta;
        
        return conta.Id;
    }
    
    public static void updateAccount(Id idConta, String name, String porteEmpresa, String status) {
        Account conta = new Account();
        conta.Id = idConta;
        conta.Name = name;
        conta.Porte_da_empresa__c = porteEmpresa;
        conta.Status__c = status;
        
        update conta;
    }
    
    //public static void upsertAccount(List<Account> contas){
        //try {
           // upsert contas CNPJ__c;
        //} catch (DmlException e){
         //   System.debug(e.getMessage());
        //}
   // }
    
}