force-app/main/default/objects/Account/fields/Porte_da_empresa__c.field-meta.xml
<CustomField>
    <fullName>Porte_da_empresa__c</fullName>
    <inlineHelpText>Pequeno (até 50 funcionários)
Médio (50 – 200 funcionários)
Grande (&gt; 200 funcionários)</inlineHelpText>
    <label>Porte da empresa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pequeno</fullName>
            </value>
            <value>
                <fullName>Médio</fullName>
            </value>
            <value>
                <fullName>Grande</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Cliente.recordType-meta.xml
<RecordType>
    <fullName>Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Companhia.recordType-meta.xml
<RecordType>
    <fullName>Companhia</fullName>
    <active>true</active>
    <label>Companhia</label>
</RecordType>

force-app/main/default/objects/Despesa__c/Despesa__c.object-meta.xml
<CustomObject>
    <label>Despesa</label>
    <nameField>
        <label>Nome da despesa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Despesa__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Pago pelo colaborador</fullName>
            </value>
            <value>
                <fullName>Pago_pela_empresa</fullName>
                <label>Pago pela empresa</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Viagem__c.field-meta.xml
<CustomField>
    <fullName>Viagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Viagem</label>
    <referenceTo>Viagem__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>V-{000000000}</displayFormat>
        <label>Número da Viagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Viagens (Cliente)</relationshipLabel>
    <relationshipName>Viagens1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Companhia__c.field-meta.xml
<CustomField>
    <fullName>Companhia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Companhia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Companhia</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Custo__c.field-meta.xml
<CustomField>
    <fullName>Custo__c</fullName>
    <inlineHelpText>Custo em reais da viagem da ida/volta.</inlineHelpText>
    <label>Custo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EstudosSOQL.cls
public class EstudosSOQL {
    public static Account getAccount(String name){
        List<Account> contas = [SELECT Id, Name, Status__c, Porte_da_Empresa__c FROM Account WHERE Name = :name];
        
        if(!contas.isEmpty()) {
            return contas[0];
        } else {
            return null;
        }
    }
    
    public static List<Despesa__c> getDesepesasByClienteCompanhia(String cliente, String colaborador) {
        List<Despesa__c> despesas = [SELECT Id, Name, Cliente__r.Name, Colaborador__r.Name FROM Despesa__c WHERE Cliente__r.Name = :cliente AND Colaborador__r.Name = :colaborador];
        
        if(!despesas.isEmpty()) {
            return despesas;
        } else {
            return null;
        }
    }
    
    public static List<Viagem__c> getViagensByClienteCompanhia(String cliente, String companhia) {
        List<Viagem__c> viagens = [SELECT Id, Name, Cliente__r.Name, Companhia__r.Name FROM Viagem__c WHERE Cliente__r.Name = :cliente AND Companhia__r.Name = :companhia];
        
        if(!viagens.isEmpty()) {
            return viagens;
        } else {
            return null;
        }
    }
    
    public static List<Account> getClientesDespesasEViagens() {
        String recordType = 'Cliente';
        List<Account> contas1 = [SELECT Name, Status__c,
                                (SELECT Custo__c FROM Despesas__r), 
                                (SELECT Custo__c FROM Viagens__r)
                                FROM Account WHERE RecordType.DeveloperName = :recordType];
        
        if(!contas1.isEmpty()) {
            return contas1;
        } else {
            return null;
        }
            
    }
    
    public static Decimal getTotalCustoDespesas(String empresa) {
        AggregateResult[] groupedResults = [SELECT Cliente__r.Name, SUM(Custo__c) custo
                                           FROM Despesa__c 
                                           WHERE Cliente__r.Name = :empresa GROUP BY Cliente__r.Name];
    	
    	Decimal totalCusto = (Decimal) groupedResults[0].get('custo');
        
        return totalCusto;
    }
}