force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Cliente.recordType-meta.xml
<RecordType>
    <fullName>Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Despesa__c/Despesa__c.object-meta.xml
<CustomObject>
    <label>Despesa</label>
    <nameField>
        <label>Nome da despesa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Despesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Despesa__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Data_da_Despesa__c.field-meta.xml
<CustomField>
    <fullName>Data_da_Despesa__c</fullName>
    <label>Data da Despesa</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Pago pelo colaborador</fullName>
            </value>
            <value>
                <fullName>Pago_pela_empresa</fullName>
                <label>Pago pela empresa</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Despesa__c/fields/Viagem__c.field-meta.xml
<CustomField>
    <fullName>Viagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Viagem</label>
    <referenceTo>Viagem__c</referenceTo>
    <relationshipLabel>Despesas</relationshipLabel>
    <relationshipName>Despesas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/Pagamento__c.object-meta.xml
<CustomObject>
    <label>Pagamento</label>
    <nameField>
        <displayFormat>PG-{000000000}</displayFormat>
        <label>Número do Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pagamento__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pagamentos</relationshipLabel>
    <relationshipName>Pagamentos1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando Pagamento</fullName>
                <default>true</default>
                <label>Aguardando Pagamento</label>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pagamento__c/fields/Valor_Total_Despesas__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total_Despesas__c</fullName>
    <label>Valor Total Despesas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pagamento__c/fields/Valor_Total_Viagens__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total_Viagens__c</fullName>
    <label>Valor Total Viagens</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>V-{000000000}</displayFormat>
        <label>Número da Viagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Viagens (Cliente)</relationshipLabel>
    <relationshipName>Viagens1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Custo__c.field-meta.xml
<CustomField>
    <fullName>Custo__c</fullName>
    <inlineHelpText>Custo em reais da viagem da ida/volta.</inlineHelpText>
    <label>Custo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Ida__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Ida__c</fullName>
    <label>Data/Hora da Ida</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Volta__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Volta__c</fullName>
    <label>Data/Hora da Volta</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <label>Cidade de Destino</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <label>Cidade de Origem</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pagamento</label>
    <referenceTo>Pagamento__c</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PagamentosGestaoController.cls
public class PagamentosGestaoController {
    
    @AuraEnabled(cacheable=true) //faz a comunicação com o LWC (ou Aura component) com o APEX
    public static List<Account> getClientesAtivos() {
       return [SELECT Name FROM Account WHERE Status__c = 'Ativo' AND RecordType.Name = 'Cliente'];
    }
	
    @AuraEnabled //faz a comunicação com o LWC (ou Aura component) com o APEX
    public static List<Viagem__c> getViagens(Id contaId, Date dataInicio, Date dataFim) {
        return [SELECT Origem__c, Destino__c, Custo__c, Data_Hora_da_Ida__c, Data_Hora_da_Volta__c, Colaborador__r.Name, Colaborador__r.FirstName FROM Viagem__c 
                WHERE Data_Hora_da_Ida__c >= :dataInicio AND Data_Hora_da_Ida__c <= :dataFim 
                AND Cliente__c = :contaId
                AND Pagamento__c = null
                ORDER BY Data_Hora_da_Ida__c
               ];
    }
    
    
    @AuraEnabled //faz a comunicação com o LWC (ou Aura component) com o APEX
    public static List<Despesa__c> getDespesas(Id contaId, Date dataInicio, Date dataFim) {
        return [SELECT Custo__c, Descricao__c, Data_da_Despesa__c, Colaborador__r.Name, Colaborador__r.FirstName FROM Despesa__c 
                WHERE Data_da_Despesa__c >= :dataInicio AND Data_da_Despesa__c <= :dataFim 
                AND Cliente__c = :contaId
                AND Pagamento__c = null
                ORDER BY Data_da_Despesa__c
               ];
    }
    
    @AuraEnabled
    public static Pagamento__c criarPagamento(Id contaId, List<Viagem__c> viagens, List<Despesa__c> despesas) {
        
        Pagamento__c pagamento = new Pagamento__c();
        pagamento.Cliente__c = contaId;
        pagamento.Status__c = 'Aguardando Pagamento';
        insert pagamento;
        
        Decimal valorTotalCustoViagem = 0;
        if(!viagens.isEmpty()) {
            for(Viagem__c viagem : viagens) {
                viagem.Pagamento__c = pagamento.Id;
                valorTotalCustoViagem += viagem.Custo__c;
            }
            update viagens;
        }
        
        Decimal valorTotalCustoDespesa = 0;
        if(!despesas.isEmpty()) {
            for(Despesa__c despesa : despesas) {
                despesa.Pagamento__c = pagamento.Id;
                valorTotalCustoDespesa += despesa.Custo__c;
            }
            update despesas;
        }
        
        pagamento.Valor_Total_Despesas__c = valorTotalCustoDespesa;
        pagamento.Valor_Total_Viagens__c = valorTotalCustoViagem;
        update pagamento;
        
       //update new Pagamento__c(Id=pagamento.Id, ValorTotalViagens__c=valorTotalCustoViagem, ValorTotalDespesas__c=valorTotalCustoDespesa);
        
        Formula.recalculateFormulas(new List<Pagamento__c>{pagamento});
        
        return pagamento;
    }
    
    
    //Não está sendo usado, mas fiz para que vocês possam estudar como retornar uma classe customizada para um LWC ou AURA especifico
    public class Pagamento{
        @AuraEnabled
        public Id pagamentoId;
        @AuraEnabled
        public Decimal valorTotal;
        
        public Pagamento(Id pagamentoId, Decimal valorTotal){
            this.pagamentoId = pagamentoId;
            this.valorTotal = valorTotal;
        }
    }


}