force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>V-{000000000}</displayFormat>
        <label>Número da Viagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/fields/Pago_pela_empresa__c.field-meta.xml
<CustomField>
    <fullName>Pago_pela_empresa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pago pela empresa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ViagemTriggerNotificaQuandoPago.cls
public class ViagemTriggerNotificaQuandoPago {
	private List<Viagem__c> newList;
    private Map<Id, Viagem__c> oldMap;
    private Map<Id, Viagem__c> filteredMap = new Map<Id, Viagem__c>(); //mapa com apenas os registros que possuem relevância para a automação na trigger
    private Boolean hasRecords;
    
    public ViagemTriggerNotificaQuandoPago(List<Viagem__c> newList, Map<Id, Viagem__c> oldMap) {
        this.newList = newList;
        this.oldMap = oldMap;
        filter();
        this.hasRecords = (filteredMap.isEmpty()) ? false : true;
    }
    
    // método que realiza lógica para mapear os registros que terão automação
    private void filter() {    
        
        for(Viagem__c viagem : newList) {
            Boolean valorAntigoDoCampoPagoEmpresa = oldMap.get(viagem.Id).Pago_pela_empresa__c;
            
            if(viagem.Pago_pela_empresa__c && viagem.Pago_pela_empresa__c != valorAntigoDoCampoPagoEmpresa) {
                 filteredMap.put(viagem.Id, viagem);
            }
        }
    }
    
    public void run() { //método que dispara (trigger) a automação
        if(hasRecords) {
            CustomNotificationType notification = [SELECT Id FROM CustomNotificationType WHERE DeveloperName = 'ViagemPaga'];
            Set<String> destinatarios = new Set<String>{ Userinfo.getUserId() };
                
            for(Viagem__c viagem : filteredMap.values()) {
                String assunto = 'A viagem ' + viagem.Name + ' foi paga pela empresa com sucesso!';
				Utils.sendCustomNotification('Viagem paga', assunto, notification.Id, viagem.Id, destinatarios);
            }
        }
    }
}