force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>V-{000000000}</displayFormat>
        <label>Número da Viagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/fields/Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CriaNotificacaoViagem.cls
public class CriaNotificacaoViagem {
    
    @InvocableMethod(label='Cria Notificacao para Viagem' description='Cria uma notificação de viagem toda vez que uma for cadastrada' category='Viagem__c')
    public static void notificarUsuario(List<Viagem__c> recipientsId) {
        CustomNotificationType notificationType = [SELECT Id, DeveloperName 
                                                   FROM CustomNotificationType 
                                                   WHERE DeveloperName='NotificarEventoNovaViagem'];
        
        Set<Id> colaboradorId = new Set<Id>();
        for (Viagem__c viagem : recipientsId) {
            colaboradorId.add(viagem.Colaborador__c);
        }
        
        Map<Id,Contact> mapContatos = new Map<Id, Contact>([Select Id, FirstName, LastName FROM Contact Where Id IN:colaboradorId]); 
        
        for (Viagem__c viagem : recipientsId) {

            Messaging.CustomNotification notification = new Messaging.CustomNotification();
            
            notification.setTitle('Uma nova viagem foi agendada');
            notification.setBody('A viagem ' + viagem.Name + ' foi criada para o contato ' + mapContatos.get(viagem.Colaborador__c).FirstName + '. Clique para ver.');
            
            notification.setNotificationTypeId(notificationType.Id);
            notification.setTargetId(viagem.Colaborador__c);
            
         try{
            notification.send(new Set<String> { Userinfo.getUserId() });
         } catch(Exception e) {
            System.debug('Problema no envio da notificação: ' + e.getMessage());
        	}
        }     
    }
}