force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>V-{000000000}</displayFormat>
        <label>Número da Viagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/fields/Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Ida__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Ida__c</fullName>
    <label>Data/Hora da Ida</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Volta__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Volta__c</fullName>
    <label>Data/Hora da Volta</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CriaNotificacaoDeAjusteViagem.cls
public class CriaNotificacaoDeAjusteViagem {
	@InvocableMethod(label='Cria Notificacao para Ajuste de Viagem' description='Cria uma notificação de ajuste de viagem se já existir algum evento no período da viagem' category='Viagem__c')
    public static void notificarUsuarioAjusteViagem(List<Viagem__c> viagens) {
        CustomNotificationType notificationType = [SELECT Id, DeveloperName 
                                                   FROM CustomNotificationType 
                                                   WHERE DeveloperName='NotificarAjusteViagem'];
        
        //List<Event> eventos = new List<Event>();
        
        for(Viagem__c viagem : viagens) {
            //for (Event evento : eventos) {
               // if(viagem.Data_Hora_da_Ida__c == evento.ActivityDateTime && viagem.Data_Hora_da_Volta__c == evento.EndDateTime && viagem.Colaborador__c == evento.WhoId) {
        
                        Messaging.CustomNotification notification = new Messaging.CustomNotification();
        
                        notification.setTitle('Uma viagem precisa ser ajustada');
                        notification.setBody('Existe um evento já criado para o período escolhido.' + ' Clique para ver.');
                        
                        notification.setNotificationTypeId(notificationType.Id);
                        notification.setTargetId(viagem.Colaborador__c);
            
                    try{
                        notification.send(new Set<String> { Userinfo.getUserId() });
                    } catch(Exception e) {
                        System.debug('Problema no envio da notificação: ' + e.getMessage());
                    }
                    
                //}

      		//}
        }

 
    }
}