force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>V-{000000000}</displayFormat>
        <label>Número da Viagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/fields/Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Viagens</relationshipLabel>
    <relationshipName>Viagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Ida__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Ida__c</fullName>
    <label>Data/Hora da Ida</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Volta__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Volta__c</fullName>
    <label>Data/Hora da Volta</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Destino__c.field-meta.xml
<CustomField>
    <fullName>Destino__c</fullName>
    <label>Cidade de Destino</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <label>Cidade de Origem</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CriaEventoViagem.cls
public class CriaEventoViagem {
    
    @InvocableMethod(label='Cria Evento para Viagem' description='Cria um evento para uma viagem a partir de sua data' category='Viagem__c')
    public static void criarEventoDataViagem(List<Viagem__c> novasViagens) {

        List<Event> eventos = new List<Event>();
        
        for(Viagem__c viagem : novasViagens) {
            Event evento = new Event();
            evento.Subject = viagem.Origem__c + ' - ' + viagem.Destino__c;
            evento.ActivityDateTime = viagem.Data_Hora_da_Ida__c;
            evento.EndDateTime = viagem.Data_Hora_da_Volta__c;
            evento.WhatId = viagem.Id;
            evento.WhoId = viagem.Colaborador__c;
            
            eventos.add(evento);
        }
        
        insert eventos;
        
    }
}