force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>V-{000000000}</displayFormat>
        <label>Número da Viagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Ida__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Ida__c</fullName>
    <label>Data/Hora da Ida</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Viagem__c/fields/Data_Hora_da_Volta__c.field-meta.xml
<CustomField>
    <fullName>Data_Hora_da_Volta__c</fullName>
    <label>Data/Hora da Volta</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ViagemTriggerValidaDataHora.cls
public class ViagemTriggerValidaDataHora {
	private List<Viagem__c> newList;
    private Map<Id, Viagem__c> oldMap;
    private Map<Id, Viagem__c> filteredMapDataVoltaInferior = new Map<Id, Viagem__c>();
    private Boolean hasRecords;
    
    public ViagemTriggerValidaDataHora(List<Viagem__c> newList, Map<Id, Viagem__c> oldMap) {
        this.newList = newList;
        this.oldMap = oldMap;
        filter();
        this.hasRecords = (filteredMapDataVoltaInferior.isEmpty()) ? false : true;
    }
    
    private void filter() {
        for (Viagem__c viagem : newList) {
            if(
                (
                    oldMap.isEmpty() || /*verifica se já tem uma viagem*/
                	viagem.Data_Hora_da_Volta__c != oldMap.get(viagem.Id).Data_Hora_da_Volta__c ||
              		viagem.Data_Hora_da_Ida__c != oldMap.get(viagem.Id).Data_Hora_da_Ida__c
                )
                
                && viagem.Data_Hora_da_Volta__c <= viagem.Data_Hora_da_Ida__c) {
                	filteredMapDataVoltaInferior.put(viagem.Id, viagem);
            }
        }
    }
    
    public void run() {
        if(!filteredMapDataVoltaInferior.isEmpty()) {
            for(Viagem__c viagem : filteredMapDataVoltaInferior.values()) {
                 viagem.addError('A data de volta não pode ser inferior a data de ida.');
            }
        }
    }
}